### ISSUE TITLE
[chapter 5-3]  Losing R permission makes no sense

### ISSUE THREAD

**Issue by Archsx** [cognitive-engineering-lab/rust-book#177]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  - chapter 5-3
- I have checked the latest `main` branch to see if this has already been fixed, in this file:
  - https://github.com/cognitive-engineering-lab/rust-book/blob/main/src/ch05-03-method-syntax.md

URL to the section(s) of the book with this problem:
https://rust-book.cs.brown.edu/ch05-03-method-syntax.html
Description of the problem:

when using a immutable reference to refer a variable, it shows the variable(rect) losses the `R` permission.
![Screenshot from 2024-04-01 14-56-34](https://github.com/cognitive-engineering-lab/rust-book/assets/21698481/c3d8587f-f718-455e-8b86-358857577fe7)

Suggested fix:

**Comment by twhentschel** [comment]
I'm still learning this, but perhaps it's because the variable `rect` is no longer used after that point in the program, so it loses all permissions.

I redid this example in aquascope (the program that makes these type of borrow-checking figures in the book) but used `rect` one more time after it was aliased and this is what I got:
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/49924808/636677bb-0201-46d9-9212-882474df441b)

**Comment by willcrichton** [comment]
@twhentschel's explanation is exactly correct. It's an open issue in Aquascope to make these cases clearer. Hopefully we will improve this soon. See: cognitive-engineering-lab/aquascope#85
