### ISSUE TITLE
Possible error on Chapter 4.3

### ISSUE THREAD

**Issue by musjj** [cognitive-engineering-lab/rust-book#96]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  - Chapter 4
- I have checked the latest `main` branch to see if this has already been fixed, in this file:
  - <https://github.com/cognitive-engineering-lab/rust-book/blob/ac62c321975f98b7021e1023c8ceceafa8311a6e/src/ch04-03-fixing-ownership-errors.md?plain=1#L213-L218>

URL to the section(s) of the book with this problem:
<https://rust-book.cs.brown.edu/ch04-03-fixing-ownership-errors.html#fixing-an-unsafe-program-copying-vs-moving-out-of-a-collection>

Description of the problem:
`v` should not lose read permission in second line.

Suggested fix:
`v` should keep its read permission.

**Comment by willcrichton** [comment]
Hi, thanks for the issue. This is one of those technically-correct but confusing behaviors right now, an instance of cognitive-engineering-lab/aquascope#85. `v` loses read permissions because it is no longer live at that line. But if you extended the live range of `v` by reading it later, that would be totally fine. As mentioned in the linked issue, we're working on a clearer explanation of this idea!
